[package]
name = "sorrel-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
jiff = { version = "0.2.35", default-features = false, features = ["std"] }
blake3 = "1.8.5"
git2 = "0.21.0"
ignore = "=0.4.23"
percent-encoding = "2.3.2"
url = "2.5.8"
serde_yaml_ng = "0.10.0"
toml = "0.9.12"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
thiserror = "2.0.18"

[dev-dependencies]
tempfile = "3.27.0"

[[bench]]
name = "engine"
harness = false

[lints]
workspace = true

[features]
git2 = []
